/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/**
 * オブジェクト `{ A1: '=1+2', ... }` を受け取り、計算後のオブジェクトを返す。
 *
 * 第2引数で `__NAME__` 形式のプレースホルダを置換する。
 * 不正な置換キーは無視し、`console.warn` を出す（計算は続行）。
 * 第3・第4引数で並列適応の閾値（層幅・仕事量）を上書きできる。省略時はエンジン既定値。
 */
export declare function calcSpreadsheet(cells: Record<string, string | number>, replacements?: Record<string, string | number> | undefined | null, minLayerWidth?: number | undefined | null, minLayerWork?: number | undefined | null): Record<string, string | number>
